/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TrssAlert {
        /**
          * This sets the color scheme for the alert.
         */
        "appearance": string;
        /**
          * The text for the headline of the alert.
         */
        "header": string;
    }
    interface TrssBanner {
        /**
          * This sets the color scheme for the alert.
         */
        "appearance": string;
        /**
          * The text for the headline of the alert.
         */
        "header": string;
    }
    interface TrssBreadcrumbs {
        /**
          * The visual separator between links.
         */
        "separator": string;
    }
    interface TrssCard {
        /**
          * The text for the headline of the card.
         */
        "header": string;
        /**
          * The alternative text for the card image.
         */
        "imageAlt": string;
        /**
          * The image included in the card.
         */
        "imageUrl": string;
    }
    interface TrssCarousel {
    }
    interface TrssEventsList {
        /**
          * Whether or not to display the event teaser.
         */
        "image": boolean;
        /**
          * Layout style of the event list.
         */
        "layout": string;
        /**
          * Limit the number of items displayed.
         */
        "limit": number;
        /**
          * Whether or not to display the event location.
         */
        "location": boolean;
        /**
          * The JSON source for the content list in this component.
         */
        "source": string;
        /**
          * Whether or not to display the event teaser.
         */
        "teaser": boolean;
    }
    interface TrssLogo {
        /**
          * Sets the color of the logo (blue or white)
         */
        "display": string;
        /**
          * The URL target for the logo.
         */
        "link": string;
        /**
          * Sets the width of the logo.
         */
        "width": string;
        /**
          * Set whether or not the logo will animate on hover
         */
        "withAnimation": boolean;
    }
    interface TrssNewsList {
        /**
          * Limit the number of items displayed.
         */
        "limit": number;
        /**
          * The JSON source for the content list in this component.
         */
        "source": string;
        /**
          * Whether or not to display the teaser text.
         */
        "teaser": boolean;
    }
    interface TrssSiteTitle {
        /**
          * Sets the URL for the title link.
         */
        "link": string;
    }
    interface TrssUcscFooter {
        /**
          * The numeric year we use for the copyright.
         */
        "year": string;
    }
    interface TrssUcscHeader {
        /**
          * The URL for the search form action attribute
         */
        "searchAction": string;
        /**
          * The query parameter for the search string
         */
        "searchQuery": string;
        /**
          * Whether or not to display the UCSC logo
         */
        "useLogo": boolean;
    }
}
declare global {
    interface HTMLTrssAlertElement extends Components.TrssAlert, HTMLStencilElement {
    }
    var HTMLTrssAlertElement: {
        prototype: HTMLTrssAlertElement;
        new (): HTMLTrssAlertElement;
    };
    interface HTMLTrssBannerElement extends Components.TrssBanner, HTMLStencilElement {
    }
    var HTMLTrssBannerElement: {
        prototype: HTMLTrssBannerElement;
        new (): HTMLTrssBannerElement;
    };
    interface HTMLTrssBreadcrumbsElement extends Components.TrssBreadcrumbs, HTMLStencilElement {
    }
    var HTMLTrssBreadcrumbsElement: {
        prototype: HTMLTrssBreadcrumbsElement;
        new (): HTMLTrssBreadcrumbsElement;
    };
    interface HTMLTrssCardElement extends Components.TrssCard, HTMLStencilElement {
    }
    var HTMLTrssCardElement: {
        prototype: HTMLTrssCardElement;
        new (): HTMLTrssCardElement;
    };
    interface HTMLTrssCarouselElement extends Components.TrssCarousel, HTMLStencilElement {
    }
    var HTMLTrssCarouselElement: {
        prototype: HTMLTrssCarouselElement;
        new (): HTMLTrssCarouselElement;
    };
    interface HTMLTrssEventsListElement extends Components.TrssEventsList, HTMLStencilElement {
    }
    var HTMLTrssEventsListElement: {
        prototype: HTMLTrssEventsListElement;
        new (): HTMLTrssEventsListElement;
    };
    interface HTMLTrssLogoElement extends Components.TrssLogo, HTMLStencilElement {
    }
    var HTMLTrssLogoElement: {
        prototype: HTMLTrssLogoElement;
        new (): HTMLTrssLogoElement;
    };
    interface HTMLTrssNewsListElement extends Components.TrssNewsList, HTMLStencilElement {
    }
    var HTMLTrssNewsListElement: {
        prototype: HTMLTrssNewsListElement;
        new (): HTMLTrssNewsListElement;
    };
    interface HTMLTrssSiteTitleElement extends Components.TrssSiteTitle, HTMLStencilElement {
    }
    var HTMLTrssSiteTitleElement: {
        prototype: HTMLTrssSiteTitleElement;
        new (): HTMLTrssSiteTitleElement;
    };
    interface HTMLTrssUcscFooterElement extends Components.TrssUcscFooter, HTMLStencilElement {
    }
    var HTMLTrssUcscFooterElement: {
        prototype: HTMLTrssUcscFooterElement;
        new (): HTMLTrssUcscFooterElement;
    };
    interface HTMLTrssUcscHeaderElement extends Components.TrssUcscHeader, HTMLStencilElement {
    }
    var HTMLTrssUcscHeaderElement: {
        prototype: HTMLTrssUcscHeaderElement;
        new (): HTMLTrssUcscHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "trss-alert": HTMLTrssAlertElement;
        "trss-banner": HTMLTrssBannerElement;
        "trss-breadcrumbs": HTMLTrssBreadcrumbsElement;
        "trss-card": HTMLTrssCardElement;
        "trss-carousel": HTMLTrssCarouselElement;
        "trss-events-list": HTMLTrssEventsListElement;
        "trss-logo": HTMLTrssLogoElement;
        "trss-news-list": HTMLTrssNewsListElement;
        "trss-site-title": HTMLTrssSiteTitleElement;
        "trss-ucsc-footer": HTMLTrssUcscFooterElement;
        "trss-ucsc-header": HTMLTrssUcscHeaderElement;
    }
}
declare namespace LocalJSX {
    interface TrssAlert {
        /**
          * This sets the color scheme for the alert.
         */
        "appearance"?: string;
        /**
          * The text for the headline of the alert.
         */
        "header"?: string;
    }
    interface TrssBanner {
        /**
          * This sets the color scheme for the alert.
         */
        "appearance"?: string;
        /**
          * The text for the headline of the alert.
         */
        "header"?: string;
    }
    interface TrssBreadcrumbs {
        /**
          * The visual separator between links.
         */
        "separator"?: string;
    }
    interface TrssCard {
        /**
          * The text for the headline of the card.
         */
        "header"?: string;
        /**
          * The alternative text for the card image.
         */
        "imageAlt"?: string;
        /**
          * The image included in the card.
         */
        "imageUrl"?: string;
    }
    interface TrssCarousel {
    }
    interface TrssEventsList {
        /**
          * Whether or not to display the event teaser.
         */
        "image"?: boolean;
        /**
          * Layout style of the event list.
         */
        "layout"?: string;
        /**
          * Limit the number of items displayed.
         */
        "limit"?: number;
        /**
          * Whether or not to display the event location.
         */
        "location"?: boolean;
        /**
          * The JSON source for the content list in this component.
         */
        "source"?: string;
        /**
          * Whether or not to display the event teaser.
         */
        "teaser"?: boolean;
    }
    interface TrssLogo {
        /**
          * Sets the color of the logo (blue or white)
         */
        "display"?: string;
        /**
          * The URL target for the logo.
         */
        "link"?: string;
        /**
          * Sets the width of the logo.
         */
        "width"?: string;
        /**
          * Set whether or not the logo will animate on hover
         */
        "withAnimation"?: boolean;
    }
    interface TrssNewsList {
        /**
          * Limit the number of items displayed.
         */
        "limit"?: number;
        /**
          * The JSON source for the content list in this component.
         */
        "source"?: string;
        /**
          * Whether or not to display the teaser text.
         */
        "teaser"?: boolean;
    }
    interface TrssSiteTitle {
        /**
          * Sets the URL for the title link.
         */
        "link"?: string;
    }
    interface TrssUcscFooter {
        /**
          * The numeric year we use for the copyright.
         */
        "year"?: string;
    }
    interface TrssUcscHeader {
        /**
          * The URL for the search form action attribute
         */
        "searchAction"?: string;
        /**
          * The query parameter for the search string
         */
        "searchQuery"?: string;
        /**
          * Whether or not to display the UCSC logo
         */
        "useLogo"?: boolean;
    }
    interface IntrinsicElements {
        "trss-alert": TrssAlert;
        "trss-banner": TrssBanner;
        "trss-breadcrumbs": TrssBreadcrumbs;
        "trss-card": TrssCard;
        "trss-carousel": TrssCarousel;
        "trss-events-list": TrssEventsList;
        "trss-logo": TrssLogo;
        "trss-news-list": TrssNewsList;
        "trss-site-title": TrssSiteTitle;
        "trss-ucsc-footer": TrssUcscFooter;
        "trss-ucsc-header": TrssUcscHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "trss-alert": LocalJSX.TrssAlert & JSXBase.HTMLAttributes<HTMLTrssAlertElement>;
            "trss-banner": LocalJSX.TrssBanner & JSXBase.HTMLAttributes<HTMLTrssBannerElement>;
            "trss-breadcrumbs": LocalJSX.TrssBreadcrumbs & JSXBase.HTMLAttributes<HTMLTrssBreadcrumbsElement>;
            "trss-card": LocalJSX.TrssCard & JSXBase.HTMLAttributes<HTMLTrssCardElement>;
            "trss-carousel": LocalJSX.TrssCarousel & JSXBase.HTMLAttributes<HTMLTrssCarouselElement>;
            "trss-events-list": LocalJSX.TrssEventsList & JSXBase.HTMLAttributes<HTMLTrssEventsListElement>;
            "trss-logo": LocalJSX.TrssLogo & JSXBase.HTMLAttributes<HTMLTrssLogoElement>;
            "trss-news-list": LocalJSX.TrssNewsList & JSXBase.HTMLAttributes<HTMLTrssNewsListElement>;
            "trss-site-title": LocalJSX.TrssSiteTitle & JSXBase.HTMLAttributes<HTMLTrssSiteTitleElement>;
            "trss-ucsc-footer": LocalJSX.TrssUcscFooter & JSXBase.HTMLAttributes<HTMLTrssUcscFooterElement>;
            "trss-ucsc-header": LocalJSX.TrssUcscHeader & JSXBase.HTMLAttributes<HTMLTrssUcscHeaderElement>;
        }
    }
}
