/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TrssAlert {
        /**
          * This sets the color scheme for the alert.
          * @default 'notice'
         */
        "appearance": string;
    }
    interface TrssBreadcrumbs {
        /**
          * Should the last item in the list look like a link?
          * @default true
         */
        "trailing_link": boolean;
    }
    interface TrssCard {
        /**
          * The text for the headline of the card.
         */
        "header": string;
        /**
          * The alternative text for the card image.
         */
        "imageAlt": string;
        /**
          * The image included in the card.
         */
        "imageUrl": string;
    }
    interface TrssCarousel {
    }
    interface TrssEventsList {
        /**
          * Whether or not to display the event teaser.
          * @default false
         */
        "image": boolean;
        /**
          * Layout style of the event list.
          * @default 'list'
         */
        "layout": string;
        /**
          * Limit the number of items displayed.
          * @default 5
         */
        "limit": number;
        /**
          * Whether or not to display the event location.
          * @default false
         */
        "location": boolean;
        /**
          * The JSON source for the content list in this component.
          * @default 'https://events.ucsc.edu/wp-json/tribe/events/v1/events'
         */
        "source": string;
        /**
          * Whether or not to display the event teaser.
          * @default false
         */
        "teaser": boolean;
    }
    interface TrssLogo {
        /**
          * Sets the color of the logo (blue or white)
         */
        "display": string;
        /**
          * The URL target for the logo.
          * @default 'https://www.ucsc.edu'
         */
        "link": string;
        /**
          * Sets the width of the logo.
         */
        "width": string;
        /**
          * Set whether or not the logo will animate on hover
         */
        "withAnimation": boolean;
    }
    interface TrssNewsList {
        /**
          * Limit the number of items displayed.
          * @default 5
         */
        "limit": number;
        /**
          * The JSON source for the content list in this component.
          * @default 'https://news.ucsc.edu/feed/json'
         */
        "source": string;
        /**
          * Whether or not to display the teaser text.
          * @default false
         */
        "teaser": boolean;
    }
    interface TrssSiteTitle {
        /**
          * Sets the URL for the title link.
         */
        "link": string;
    }
    interface TrssUcscFooter {
        /**
          * Whether or not to display the Sammy illustration
          * @default true
         */
        "hasSammy": boolean;
        /**
          * The numeric year we use for the copyright.
          * @default new Date().getFullYear().toString()
         */
        "year": string;
    }
    interface TrssUcscHeader {
        /**
          * The URL for the search form action attribute
         */
        "searchAction": string;
        /**
          * The query parameter for the search string
         */
        "searchQuery": string;
        /**
          * Whether or not to display the UCSC logo
         */
        "useLogo": boolean;
    }
    interface TrssYouBelong {
        /**
          * This sets the color scheme for the alert.
          * @default 'blue'
         */
        "appearance": string;
        /**
          * The text for the headline of the alert.
          * @default 'You Belong Here'
         */
        "header": string;
    }
}
declare global {
    interface HTMLTrssAlertElement extends Components.TrssAlert, HTMLStencilElement {
    }
    var HTMLTrssAlertElement: {
        prototype: HTMLTrssAlertElement;
        new (): HTMLTrssAlertElement;
    };
    interface HTMLTrssBreadcrumbsElement extends Components.TrssBreadcrumbs, HTMLStencilElement {
    }
    var HTMLTrssBreadcrumbsElement: {
        prototype: HTMLTrssBreadcrumbsElement;
        new (): HTMLTrssBreadcrumbsElement;
    };
    interface HTMLTrssCardElement extends Components.TrssCard, HTMLStencilElement {
    }
    var HTMLTrssCardElement: {
        prototype: HTMLTrssCardElement;
        new (): HTMLTrssCardElement;
    };
    interface HTMLTrssCarouselElement extends Components.TrssCarousel, HTMLStencilElement {
    }
    var HTMLTrssCarouselElement: {
        prototype: HTMLTrssCarouselElement;
        new (): HTMLTrssCarouselElement;
    };
    interface HTMLTrssEventsListElement extends Components.TrssEventsList, HTMLStencilElement {
    }
    var HTMLTrssEventsListElement: {
        prototype: HTMLTrssEventsListElement;
        new (): HTMLTrssEventsListElement;
    };
    interface HTMLTrssLogoElement extends Components.TrssLogo, HTMLStencilElement {
    }
    var HTMLTrssLogoElement: {
        prototype: HTMLTrssLogoElement;
        new (): HTMLTrssLogoElement;
    };
    interface HTMLTrssNewsListElement extends Components.TrssNewsList, HTMLStencilElement {
    }
    var HTMLTrssNewsListElement: {
        prototype: HTMLTrssNewsListElement;
        new (): HTMLTrssNewsListElement;
    };
    interface HTMLTrssSiteTitleElement extends Components.TrssSiteTitle, HTMLStencilElement {
    }
    var HTMLTrssSiteTitleElement: {
        prototype: HTMLTrssSiteTitleElement;
        new (): HTMLTrssSiteTitleElement;
    };
    interface HTMLTrssUcscFooterElement extends Components.TrssUcscFooter, HTMLStencilElement {
    }
    var HTMLTrssUcscFooterElement: {
        prototype: HTMLTrssUcscFooterElement;
        new (): HTMLTrssUcscFooterElement;
    };
    interface HTMLTrssUcscHeaderElement extends Components.TrssUcscHeader, HTMLStencilElement {
    }
    var HTMLTrssUcscHeaderElement: {
        prototype: HTMLTrssUcscHeaderElement;
        new (): HTMLTrssUcscHeaderElement;
    };
    interface HTMLTrssYouBelongElement extends Components.TrssYouBelong, HTMLStencilElement {
    }
    var HTMLTrssYouBelongElement: {
        prototype: HTMLTrssYouBelongElement;
        new (): HTMLTrssYouBelongElement;
    };
    interface HTMLElementTagNameMap {
        "trss-alert": HTMLTrssAlertElement;
        "trss-breadcrumbs": HTMLTrssBreadcrumbsElement;
        "trss-card": HTMLTrssCardElement;
        "trss-carousel": HTMLTrssCarouselElement;
        "trss-events-list": HTMLTrssEventsListElement;
        "trss-logo": HTMLTrssLogoElement;
        "trss-news-list": HTMLTrssNewsListElement;
        "trss-site-title": HTMLTrssSiteTitleElement;
        "trss-ucsc-footer": HTMLTrssUcscFooterElement;
        "trss-ucsc-header": HTMLTrssUcscHeaderElement;
        "trss-you-belong": HTMLTrssYouBelongElement;
    }
}
declare namespace LocalJSX {
    interface TrssAlert {
        /**
          * This sets the color scheme for the alert.
          * @default 'notice'
         */
        "appearance"?: string;
    }
    interface TrssBreadcrumbs {
        /**
          * Should the last item in the list look like a link?
          * @default true
         */
        "trailing_link"?: boolean;
    }
    interface TrssCard {
        /**
          * The text for the headline of the card.
         */
        "header"?: string;
        /**
          * The alternative text for the card image.
         */
        "imageAlt"?: string;
        /**
          * The image included in the card.
         */
        "imageUrl"?: string;
    }
    interface TrssCarousel {
    }
    interface TrssEventsList {
        /**
          * Whether or not to display the event teaser.
          * @default false
         */
        "image"?: boolean;
        /**
          * Layout style of the event list.
          * @default 'list'
         */
        "layout"?: string;
        /**
          * Limit the number of items displayed.
          * @default 5
         */
        "limit"?: number;
        /**
          * Whether or not to display the event location.
          * @default false
         */
        "location"?: boolean;
        /**
          * The JSON source for the content list in this component.
          * @default 'https://events.ucsc.edu/wp-json/tribe/events/v1/events'
         */
        "source"?: string;
        /**
          * Whether or not to display the event teaser.
          * @default false
         */
        "teaser"?: boolean;
    }
    interface TrssLogo {
        /**
          * Sets the color of the logo (blue or white)
         */
        "display"?: string;
        /**
          * The URL target for the logo.
          * @default 'https://www.ucsc.edu'
         */
        "link"?: string;
        /**
          * Sets the width of the logo.
         */
        "width"?: string;
        /**
          * Set whether or not the logo will animate on hover
         */
        "withAnimation"?: boolean;
    }
    interface TrssNewsList {
        /**
          * Limit the number of items displayed.
          * @default 5
         */
        "limit"?: number;
        /**
          * The JSON source for the content list in this component.
          * @default 'https://news.ucsc.edu/feed/json'
         */
        "source"?: string;
        /**
          * Whether or not to display the teaser text.
          * @default false
         */
        "teaser"?: boolean;
    }
    interface TrssSiteTitle {
        /**
          * Sets the URL for the title link.
         */
        "link"?: string;
    }
    interface TrssUcscFooter {
        /**
          * Whether or not to display the Sammy illustration
          * @default true
         */
        "hasSammy"?: boolean;
        /**
          * The numeric year we use for the copyright.
          * @default new Date().getFullYear().toString()
         */
        "year"?: string;
    }
    interface TrssUcscHeader {
        /**
          * The URL for the search form action attribute
         */
        "searchAction"?: string;
        /**
          * The query parameter for the search string
         */
        "searchQuery"?: string;
        /**
          * Whether or not to display the UCSC logo
         */
        "useLogo"?: boolean;
    }
    interface TrssYouBelong {
        /**
          * This sets the color scheme for the alert.
          * @default 'blue'
         */
        "appearance"?: string;
        /**
          * The text for the headline of the alert.
          * @default 'You Belong Here'
         */
        "header"?: string;
    }

    interface TrssAlertAttributes {
        "appearance": string;
    }
    interface TrssBreadcrumbsAttributes {
        "trailing_link": boolean;
    }
    interface TrssCardAttributes {
        "imageUrl": string;
        "imageAlt": string;
        "header": string;
    }
    interface TrssEventsListAttributes {
        "source": string;
        "limit": number;
        "location": boolean;
        "teaser": boolean;
        "image": boolean;
        "layout": string;
    }
    interface TrssLogoAttributes {
        "display": string;
        "withAnimation": boolean;
        "width": string;
        "link": string;
    }
    interface TrssNewsListAttributes {
        "source": string;
        "limit": number;
        "teaser": boolean;
    }
    interface TrssSiteTitleAttributes {
        "link": string;
    }
    interface TrssUcscFooterAttributes {
        "hasSammy": boolean;
        "year": string;
    }
    interface TrssUcscHeaderAttributes {
        "useLogo": boolean;
        "searchAction": string;
        "searchQuery": string;
    }
    interface TrssYouBelongAttributes {
        "appearance": string;
        "header": string;
    }

    interface IntrinsicElements {
        "trss-alert": Omit<TrssAlert, keyof TrssAlertAttributes> & { [K in keyof TrssAlert & keyof TrssAlertAttributes]?: TrssAlert[K] } & { [K in keyof TrssAlert & keyof TrssAlertAttributes as `attr:${K}`]?: TrssAlertAttributes[K] } & { [K in keyof TrssAlert & keyof TrssAlertAttributes as `prop:${K}`]?: TrssAlert[K] };
        "trss-breadcrumbs": Omit<TrssBreadcrumbs, keyof TrssBreadcrumbsAttributes> & { [K in keyof TrssBreadcrumbs & keyof TrssBreadcrumbsAttributes]?: TrssBreadcrumbs[K] } & { [K in keyof TrssBreadcrumbs & keyof TrssBreadcrumbsAttributes as `attr:${K}`]?: TrssBreadcrumbsAttributes[K] } & { [K in keyof TrssBreadcrumbs & keyof TrssBreadcrumbsAttributes as `prop:${K}`]?: TrssBreadcrumbs[K] };
        "trss-card": Omit<TrssCard, keyof TrssCardAttributes> & { [K in keyof TrssCard & keyof TrssCardAttributes]?: TrssCard[K] } & { [K in keyof TrssCard & keyof TrssCardAttributes as `attr:${K}`]?: TrssCardAttributes[K] } & { [K in keyof TrssCard & keyof TrssCardAttributes as `prop:${K}`]?: TrssCard[K] };
        "trss-carousel": TrssCarousel;
        "trss-events-list": Omit<TrssEventsList, keyof TrssEventsListAttributes> & { [K in keyof TrssEventsList & keyof TrssEventsListAttributes]?: TrssEventsList[K] } & { [K in keyof TrssEventsList & keyof TrssEventsListAttributes as `attr:${K}`]?: TrssEventsListAttributes[K] } & { [K in keyof TrssEventsList & keyof TrssEventsListAttributes as `prop:${K}`]?: TrssEventsList[K] };
        "trss-logo": Omit<TrssLogo, keyof TrssLogoAttributes> & { [K in keyof TrssLogo & keyof TrssLogoAttributes]?: TrssLogo[K] } & { [K in keyof TrssLogo & keyof TrssLogoAttributes as `attr:${K}`]?: TrssLogoAttributes[K] } & { [K in keyof TrssLogo & keyof TrssLogoAttributes as `prop:${K}`]?: TrssLogo[K] };
        "trss-news-list": Omit<TrssNewsList, keyof TrssNewsListAttributes> & { [K in keyof TrssNewsList & keyof TrssNewsListAttributes]?: TrssNewsList[K] } & { [K in keyof TrssNewsList & keyof TrssNewsListAttributes as `attr:${K}`]?: TrssNewsListAttributes[K] } & { [K in keyof TrssNewsList & keyof TrssNewsListAttributes as `prop:${K}`]?: TrssNewsList[K] };
        "trss-site-title": Omit<TrssSiteTitle, keyof TrssSiteTitleAttributes> & { [K in keyof TrssSiteTitle & keyof TrssSiteTitleAttributes]?: TrssSiteTitle[K] } & { [K in keyof TrssSiteTitle & keyof TrssSiteTitleAttributes as `attr:${K}`]?: TrssSiteTitleAttributes[K] } & { [K in keyof TrssSiteTitle & keyof TrssSiteTitleAttributes as `prop:${K}`]?: TrssSiteTitle[K] };
        "trss-ucsc-footer": Omit<TrssUcscFooter, keyof TrssUcscFooterAttributes> & { [K in keyof TrssUcscFooter & keyof TrssUcscFooterAttributes]?: TrssUcscFooter[K] } & { [K in keyof TrssUcscFooter & keyof TrssUcscFooterAttributes as `attr:${K}`]?: TrssUcscFooterAttributes[K] } & { [K in keyof TrssUcscFooter & keyof TrssUcscFooterAttributes as `prop:${K}`]?: TrssUcscFooter[K] };
        "trss-ucsc-header": Omit<TrssUcscHeader, keyof TrssUcscHeaderAttributes> & { [K in keyof TrssUcscHeader & keyof TrssUcscHeaderAttributes]?: TrssUcscHeader[K] } & { [K in keyof TrssUcscHeader & keyof TrssUcscHeaderAttributes as `attr:${K}`]?: TrssUcscHeaderAttributes[K] } & { [K in keyof TrssUcscHeader & keyof TrssUcscHeaderAttributes as `prop:${K}`]?: TrssUcscHeader[K] };
        "trss-you-belong": Omit<TrssYouBelong, keyof TrssYouBelongAttributes> & { [K in keyof TrssYouBelong & keyof TrssYouBelongAttributes]?: TrssYouBelong[K] } & { [K in keyof TrssYouBelong & keyof TrssYouBelongAttributes as `attr:${K}`]?: TrssYouBelongAttributes[K] } & { [K in keyof TrssYouBelong & keyof TrssYouBelongAttributes as `prop:${K}`]?: TrssYouBelong[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "trss-alert": LocalJSX.IntrinsicElements["trss-alert"] & JSXBase.HTMLAttributes<HTMLTrssAlertElement>;
            "trss-breadcrumbs": LocalJSX.IntrinsicElements["trss-breadcrumbs"] & JSXBase.HTMLAttributes<HTMLTrssBreadcrumbsElement>;
            "trss-card": LocalJSX.IntrinsicElements["trss-card"] & JSXBase.HTMLAttributes<HTMLTrssCardElement>;
            "trss-carousel": LocalJSX.IntrinsicElements["trss-carousel"] & JSXBase.HTMLAttributes<HTMLTrssCarouselElement>;
            "trss-events-list": LocalJSX.IntrinsicElements["trss-events-list"] & JSXBase.HTMLAttributes<HTMLTrssEventsListElement>;
            "trss-logo": LocalJSX.IntrinsicElements["trss-logo"] & JSXBase.HTMLAttributes<HTMLTrssLogoElement>;
            "trss-news-list": LocalJSX.IntrinsicElements["trss-news-list"] & JSXBase.HTMLAttributes<HTMLTrssNewsListElement>;
            "trss-site-title": LocalJSX.IntrinsicElements["trss-site-title"] & JSXBase.HTMLAttributes<HTMLTrssSiteTitleElement>;
            "trss-ucsc-footer": LocalJSX.IntrinsicElements["trss-ucsc-footer"] & JSXBase.HTMLAttributes<HTMLTrssUcscFooterElement>;
            "trss-ucsc-header": LocalJSX.IntrinsicElements["trss-ucsc-header"] & JSXBase.HTMLAttributes<HTMLTrssUcscHeaderElement>;
            "trss-you-belong": LocalJSX.IntrinsicElements["trss-you-belong"] & JSXBase.HTMLAttributes<HTMLTrssYouBelongElement>;
        }
    }
}
